version: '3.8'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    expose:
      - '3306'
    networks:
      - go-ecom
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/0_init.sql
  go-ecom-user:
    build: ./user
    command: /user/user serve-http
    environment:
      ENVIRONMENT: DOCKER
    depends_on:
      - db
    ports:
    - "36999:36999"
    networks:
      - go-ecom
    restart: on-failure
  go-ecom-product:
    build: ./product
    command: /product/product serve-http
    environment:
      ENVIRONMENT: DOCKER
    depends_on:
      - db
    ports:
    - "36997:36997"
    networks:
      - go-ecom
    restart: on-failure
  go-ecom-order:
    build: ./order
    command: /order/order serve-http
    environment:
      ENVIRONMENT: DOCKER
    depends_on:
      - db
    ports:
    - "36998:36998"
    networks:
      - go-ecom
    restart: on-failure
  redis:
    image: redis
    ports:
    - '6379:6379'
    networks:
      - go-ecom
    restart: always
networks:
  go-ecom:
    driver: bridge