package constants

const (
	ENVIRONMENT            = "ENVIRONMENT"
	ENVIRONMENT_PRODUCTION = "PRODUCTION"
	ENVIRONMENT_STAGING    = "STAGING"
	PORT                   = "PORT"
)

const (
	MYSQL_DATABASE_NAME = "MYSQL_DATABASE_NAME"
	MYSQL_HOST          = "MYSQL_HOST"
	MYSQL_PORT          = "MYSQL_PORT"
	MYSQL_USERNAME      = "MYSQL_USERNAME"
	MYSQL_PASSWORD      = "MYSQL_PASSWORD"

	REDIS_HOST = "REDIS_HOST"
	REDIS_PORT = "REDIS_PORT"
)

const (
	JWT_SECRET = "JWT_SECRET"
)
