MYSQL_DATABASE_NAME: go_ecom_order
MYSQL_HOST: db
MYSQL_PORT: 3306
MYSQL_USERNAME: user
MYSQL_PASSWORD: password
MYSQL_CONNECTION_MAX_IDLE_TIME: 120

REDIS_HOST: redis
REDIS_PORT: 6379

PORT: 36998

HOST_PRODUCT: http://go-ecom-product:36997
BASE_PRODUCT: /api/v1
X_API_KEY_PRODUCT: 018b399d-fd63-76db-a858-e4b67141a81d
